"""
Django settings for ProjectTime project.

Generated by 'django-admin startproject' using Django 3.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-jemncuf4w__9kmx$7)0xwco$u$mca+7(&5rm3y$%puj5&8u&y('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "proj",
    'django.contrib.admin',
    "webpush",
    "recurrence",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ProjectTime.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ["templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'proj.processor.google_account_connected',
            ],
        },
    },
]

WSGI_APPLICATION = 'ProjectTime.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': "newdb",
        "USER": "iamnagasatya",
        "PASSWORD": "lwBGoH54EuNaod8qct02BgIhEYBPedz4",
        "HOST" : "dpg-cnhjg1i1hbls73cu5klg-a.singapore-postgres.render.com",
        "PORT" : 5432,
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

USE_TZ = True


LOGIN_URL = "/login"
LOGIN_REDIRECT_URL = "/"


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

STATICFILES_DIRS = [
    BASE_DIR / "static"
]

STATIC_ROOT = BASE_DIR / 'staticfiles'


# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

WEBPUSH_SETTINGS = {
    "VAPID_PUBLIC_KEY": "BG6jaufDdXHUegvelzB2muGY2UhLtZd3qycqezR2w9pqIX6Ef51hqbtoc9ZgcMuv2nxnqp0XzKLVUdxWJ9iTVUA",
    "VAPID_PRIVATE_KEY":"3rpKrdB0wnbCZbK6f-dB3bQpsZVTfdFx1lmOogtstXc",
    "VAPID_ADMIN_EMAIL": "n.nagasatyasai@gmail.com"
}

# Celery Configuration Options
CELERY_TIMEZONE = 'Asia/Kolkata'
CELERY_BROKER_URL = "redis://default:PHTn8NZcrlXCkiVKyY1yP7Arsxk0TLsM@redis-18726.c325.us-east-1-4.ec2.cloud.redislabs.com:18726/0"
CELERY_RESULT_BACKEND = "redis://default:PHTn8NZcrlXCkiVKyY1yP7Arsxk0TLsM@redis-18726.c325.us-east-1-4.ec2.cloud.redislabs.com:18726/0"

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"