# Generated by Django 3.2.2 on 2024-02-03 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0002_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('deadline', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('is_important', models.BooleanField(default=False)),
                ('is_fixed', models.BooleanField(default=False)),
                ('has_intrest', models.BooleanField(default=False)),
            ],
        ),
    ]
