# Generated by Django 3.2.2 on 2024-03-24 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0003_auto_20240324_0946'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manager',
        ),
    ]
