# Generated by Django 3.2.2 on 2024-03-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0004_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_by',
            field=models.ManyToManyField(related_name='tasks', to='proj.Student'),
        ),
    ]
