# Generated by Django 3.2.2 on 2024-03-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0005_task_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
