# Generated by Django 3.2.2 on 2024-03-11 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proj', '0008_rename_scopes_googleauth_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googleauth',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gauth', to=settings.AUTH_USER_MODEL),
        ),
    ]
