# Generated by Django 3.2.2 on 2024-03-12 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0010_remove_googleauth_id_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='event_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
