# Generated by Django 3.2.2 on 2024-03-13 05:22

from django.db import migrations, models
import proj.models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0011_task_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='schedule_after',
            field=models.DateTimeField(default=proj.models.get_now),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=proj.models.get_now_with_hour),
        ),
        migrations.AlterField(
            model_name='task',
            name='duration',
            field=models.DurationField(default='01:00:00'),
        ),
    ]
