# Generated by Django 3.2.2 on 2024-03-13 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0012_auto_20240313_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='schedule_after',
        ),
    ]
