# Generated by Django 3.2.2 on 2024-03-13 15:23

from django.db import migrations, models
import proj.models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0013_remove_task_schedule_after'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='schedule_after',
            field=models.DateTimeField(default=proj.models.get_now),
        ),
    ]
