name: Trigger auto deployment for container-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/container-app-AutoDeployTrigger-f7a6a221-3c90-4fae-89f2-a6fe61cecf11.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CONTAINERAPP_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: iamnagasatya.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPP_REGISTRY_PASSWORD }}
          containerAppName: container-app
          resourceGroup: mycontainers
          imageToBuild: iamnagasatya.azurecr.io/spm:${{ github.sha }}
          
            

     

